// <auto-generated />
namespace Bike_Rental_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class rentals : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rentals));
        
        string IMigrationMetadata.Id
        {
            get { return "202306252249075_rentals"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
